global:
  registry: docker.io
  projectPath: mendhak/http-https-echo

app:
  image:
    tag: "34"
    pullPolicy: "Always"
    livenessPath: "/"
  readinessProbe: 
    path: "/"
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 5
  livenessProbe: 
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 5
  startupProbe: 
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 5
  containerPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: "800m"
      memory: "1024Mi"  
    limits:
      cpu: "1500m"
      memory: "1024Mi"
  strategy:
    maxSurge: 1
    maxUnavailable: 0
  preStopSleep: 15
  terminationGracePeriodSeconds: 70

service:
  type: "ClusterIP"
  port: 80

configMap:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "DEBUG"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80