global:
  registry: docker.io
  projectPath: mendhak/http-https-echo

app:
  revisionHistoryLimit: 5
  image:
    tag: "34"
    pullPolicy: "Always"
    livenessPath: "/"
  readinessProbe: 
    path: "/"
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 5
  livenessProbe: 
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 5
  startupProbe: 
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 5
  containerPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: "50m" # REQUIRED: HPA uses this as the 100% baseline
      memory: "64Mi" # REQUIRED: HPA uses this as the 100% baseline  
    limits:
      cpu: "150m"
      memory: "128Mi"
  strategy:
    maxSurge: 1
    maxUnavailable: 0
  preStopSleep: 15
  terminationGracePeriodSeconds: 70

service:
  type: "ClusterIP"
  port: 80

configMap:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "DEBUG"

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1  # Use either minAvailable OR maxUnavailable, not both

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
