apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.app.strategy.maxSurge }}
      maxUnavailable: {{ .Values.app.strategy.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        # Forces a manual rollout if the configmap changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.global.projectPath }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.app.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}

          startupProbe:
            httpGet:
              path: {{ .Values.app.startupProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.startupProbe.timeoutSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}

          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-configmap"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep {{ .Values.app.preStopSleep }}"]
      # volumes:
      #   - name: config-files-volume
      #     configMap:
      #       name: "{{ .Release.Name }}-config-files"
      #   - name: tmp-volume
      #     emptyDir: {}
      
      # Must be > preStopSleep
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}