apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Release.Name }}
# Security Best Practice: Don't mount the API token unless needed
automountServiceAccountToken: false